<img src = 'https://drive.google.com/uc?id=1cPtoRUIVZ2jWaiIl8z1fm4R4V3kwQfZh
' width="170" height="190" align = "left">
# <font color = "darkgreen" > <b>Obiective</b></font>
---

În această lecție veți învăța despre:
- pachetul `numpy`
- tablouri multi-dimensionale
- generarea numerelor aleatoare





 |  |
 |---------|
 |<img src='https://drive.google.com/uc?id=1HV8Tdtn20fD2wdlz1hXrFRvgyQ-ZATIv' width="550"  ><figcaption align = "center"> |

# Numpy

" `Numpy` este pachetul de bază pentru efectuararea operațiilor științifice în Python. El conține, printre altele:

* un obiect de tip tablou N-dimensional
* funcții complexe pentru manipularea tablourilor
* elemente de algebră liniară [...] și  capacitatea de a lucra cu numere generate aleator"
( conform paginii oficiale [Numpy](https://numpy.org/))

În ML se folosesc în mod frecvent tablourile multi-dimensionale și sunt efectuate diferite tipuri de operații matematice cu acestea. Librăria `PyTorch`, care poate fi folosită pentru lucrul cu rețele neuronale, se bazează pe `numpy`. Prin urmare, este necesar să vă familiarizați cu operațiile cu tablouri multidimensionale

#Lista atributelor/ funcțiilor `numpy` folosite

| atribut/ funcție | descriere                                    |
|------------------|----------------------------------------------|
| len              | numărul de elemente al primei dimensiuni     |
| dtype            | tipul elementelor tabloului (e.g. float/int) |
| shape            | returnează un tuplu cu lungimea fiecărei dimensiuni din tablou      |
| reshape          | modifică structura unui tablou               |
| ndim             | numărul dimensiunilor tabloului              |
| size             | numărul total de elemente                    |

## Tablouri multidimensionale

> Un tablou (`array`) este un set de date cu valori de același tip.

Un tablou unidimensional (vector) ar putea fi format, de exemplu, din înălțimile tuturor elevilor dintr-o clasă: `[1.55, 1.78, 1.66, ...]`.

Un tablou de tablouri (vector de vectori sau matrice) este un tablou bidimensional (2D).

Un tablou de matrice este un tablou tridimensional (3D) ș.a.m.d.

>Generalizând, numim un astfel de obiect *tablou multidimensional* ( chiar și în cazul tabloului cu dimensiunea 1 - care este considerat un caz particular al unui tablou multidimensional)


În capitolul anterior am reprezentat grafic puncte 2D. Datele au fost memorate în liste separate: o lista pentru valorile de pe axa `Ox` și una pentru valorile de pe axa `Oy`.

Putem obține același rezultat folosind un tablou 2D `numpy`.

În continuare vom analiza câteva exemple de tablouri cu dimensiuni superioare.   


---



Vom considera câțiva indicatori ai calității aerului din România (sursa datelor [aici](https://aqicn.org/data-platform/covid19/verify/01e7b854-cffe-4f1b-877f-c433665f9c42)).

Putem reprezenta particulele ${PM_{10}}$ (particule cu diametru mai mic de 10 microni) care sunt periculoase pentru sistemul respirator.

Vom folosi un tablou bidimensional (matrice): pe coloane memorăm locația, iar pe linii datele calendaristice în care au fost efectuate măsuratorile.

Pentru a ține evidența mai multor indicatori, cum ar fi temperatura sau dioxidul de sulf (${SO_2}$), vom adăuga o a treia dimensiune și astfel se obține un tablou 3D.
![table](https://drive.google.com/uc?export=view&id=1en9jkU2xk6tovCbTPX7yeb7SvXx8b1Z5)

Să presupunem că vrem să calculam media aritmetică a valorilor ${PM_{10}}$ măsurate într-o zi în toate orașele sau media aritmetică a tuturor măsuratorilor efectuate pentru un anumit oraș.

Veți vedea cum, folosindu-ne de tablouri `numpy`, efectuarea acestor calcule se face într-un mod extrem de ușor.

Vom folosi și funcțiile din biblioteca `matplotlib` pentru o reprezentare grafică relevantă.


>Pentru început, vom încărca datele despre calitatea aerului din fișierul `airqro.csv`.

❗️❗️ Înainte, încărcați fișierul din folderul [resources](https://drive.google.com/drive/folders/1M9otFTE7NsY-zBa9CCOTnZLuXF3a9qEj?usp=sharing) în mașina virtuală.

Datele din fișierul `.csv` vor fi extrase în liste de date:
  - `locations`, pentru orașe
  - `indicators`, pentru tipul de măsuratori: ${PM_{10}}$,  ${SO_2}$ și temperatură


In [ ]:
# Avem date despre calitatea aerului pentru următoarele locații
locations = [f'Arad', f'Bacău', f'Baia Mare', f'Brăila', f'Brașov', f'Bucharest',
             f'Cluj-Napoca', f'Constanța', f'Craiova', f'Galați', f'Iași',
             f'Oradea', f'Piteşti', f'Ploieşti', f'Râmnicu Vâlcea', f'Sibiu',
             f'Timișoara']

In [ ]:
# We have air quality data for the following locations
locations = [f'Arad', f'Bacău', f'Baia Mare', f'Brăila', f'Braşov', f'Bucharest',
             f'Cluj-Napoca', f'Constanţa', f'Craiova', f'Galaţi',f'Iaşi',
             f'Oradea', f'Piteşti', f'Ploieşti', f'Râmnicu Vâlcea', f'Sibiu',
             f'Timişoara']

In [ ]:
# Avem măsurători pentru următorii indicatori
indicators = [f'pm10', f'so2', f'temperature']

Fiecare linie a fișierului .csv conține: data, orașul, tipul indicatorului, valoarea măsurată.

Datele sunt ordonate după indicator, apoi după oraș și dată.

Există 62 de înregistrări zilnice pentru fiecare locație, un total de `3162` linii = `62` zile * `17` locații * `3` indicatori (pm10, so2, temperatură)

Se vor crea 3 liste de date, câte una pentru fiecare indicator: `pm10_values, so2_values, temperature_values`


In [ ]:
import csv
num_days = 62
num_locations = len(locations) # 17
num_indicators = len(indicators) # 3
fname = '/content/airqro.csv'
pm10_values = []
so2_values = []
temperature_values = []
def extract_values(inputs):
  return float(inputs[-1])
  num_lines = 0
  with open(fname) as csvfile:
    datareader = csv.reader(csvfile)
    for row in datareader:
      val = extract_value(row)
      if 'pm10' in row:
        pm10_values.append(val)
      elif 'so2' in row:
        so2_values.append(val)
      else:
        temperature_values.append(val)
      num_lines = num_lines + 1
    csvfile.close()
  print(num_lines)


In [ ]:
# Fiecare linie din fișierul csv conține: dată, oraș, indicator, valoare mediană.
# Datele sunt sortate după indicator, apoi după oraș, apoi după dată.
"""
    Există 62 de citiri zilnice pe locație și pe indicator, pentru un total de
3162 linii = 62 de zile * 17 locații * 3 indicatori (pm10, so2, temperatură)
"""
import csv
num_days = 62
num_locations = len(locations)  # 17
num_indicators = len(indicators)  # 3
fname = '/content/airqro.csv'
pm10_values = []
so2_values = []
temperature_values = []

# definiți o funcție pentru extragerea valorii indicatorului dintr-o linie din fișier
def extract_value(inputs):
  # valoarea dobânzii este pe ultima poziție; convertiți în număr
  return float(inputs[-1])

# vom citi valorile pentru fiecare indicator
num_lines = 0
with open(fname) as csvfile:
  datareader = csv.reader(csvfile)
  for row in datareader:
    # extract numeric value from row and add it to the corresponding list
    val = extract_value(row)
    if 'pm10' in row:
      pm10_values.append(val)
    elif 'so2' in row:
      so2_values.append(val)
    else:
      temperature_values.append(val)
    num_lines += 1
  csvfile.close()

# tipăriți numărul de linii citite pentru a vă asigura că datele sunt cele așteptate
print(num_lines)

3162


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Verificăm numărul de elemente din fiecare listă creată. ( 62 de zile * 17 orașe = 1054 valori)

In [ ]:
len(pm10_values)

0

In [ ]:
len(so2_values)

0

In [ ]:
len(temperature_values)

0

In [ ]:
# Check the number of elements in each list
len(pm10_values)
#len(so2_values)
#len(temperature_values)

0

## Crearea tablourilor `numpy` din listele de valori

Pentru a lucra mai ușor cu datele, vom transfera valorile din liste în tablouri `numpy`

In [ ]:
import numpy as np
pm10_np = np.array(pm10_values)
so2_np = np.array(so2_values)
temperature_np = np.array(temperature_values)

In [ ]:
# Vom crea acum matrice numpy din aceste liste pentru o manipulare mai ușoară
import numpy as np
pm10_np = np.array(pm10_values)
so2_np = np.array(so2_values)
temperature_np = np.array(temperature_values)

 Se va afișa numărul de elemente ale primei dimensiuni `numpy` folosind atributul `shape`.


> ❗️❗️❗️ `shape` afișează un *tuplu* de valori, fiecare element din tuplu reprezentând numărul de elemente al unei dimensiuni a tabloului.


> Vă reamintim că ați învățat despre *tupluri* în `Python` în [ Lecția 7 - Tupluri](https://www.pyml.ro/lectia-07-tupluri-in-python-01.php)



In [ ]:
# Să vedem formele acestor matrice folosind atributul „shape”.
pm10_np.shape

(0,)

In [ ]:
so2_np.shape

(0,)

In [ ]:
temperature_np.shape

(0,)

Afișăm primele 10 elemente ale tabloului `pm10_np`

In [ ]:
pm10_np[:10]

array([], dtype=float64)

Afișam primele 10 elemente ale tabloului so2_np

In [ ]:
so2_np [ : 10 ]

array([], dtype=float64)

Afișăm primele 10 elemente ale tabloului temperature_np

In [ ]:
temperature_np [ : 10 ]

array([], dtype=float64)

Vedem tipul elementelor tabloului `pm10_np` folosind atributul `dtype`

In [ ]:
# Verificați tipul folosind atributul „dtype”.
pm10_np.dtype

dtype('float64')

In [ ]:
so2_np.dtype

dtype('float64')

In [ ]:
temperature_np.dtype

dtype('float64')

Vom modifica structura tablourilor, adăugand coloana pentru locație, fără a modifica datele existente.
Vom folosi funcția `reshape` cu parametrul  `order ='F'`, parcurgerea efectuându-se pe linie.

In [ ]:
so2_np = so2_np.reshape([num_days, num_locations], order='F')

ValueError: cannot reshape array of size 0 into shape (62,17)

In [ ]:
temperature_np = temperature_np.reshape([num_days, num_locations], order = 'F')

ValueError: cannot reshape array of size 0 into shape (62,17)

In [ ]:
"""
    Să remodelăm fiecare matrice pentru a avea fiecare locație ca o nouă coloană;
noi vom folosi „reshape” cu parametrul de ordine = „F”, astfel încât prima
dimensiune (rândul) de modificări cel mai rapid"
"""
pm10_np = pm10_np.reshape([num_days, num_locations], order='F')

Afișăm primele 10 valori pentru prima locație.

In [ ]:
pm10_np[:10, 0]

In [ ]:
so2_np[: 10, 0]

In [ ]:
temperature_np[: 10, 0]

Verifcăm din nou numărul elementelor din prima dimensiune a tabloului ( 62 de înregistrări pentru 17 orașe)

In [ ]:
# Verificați din nou forma
pm10_np.shape

In [ ]:
so2_np.shape

In [ ]:
temperature_np.shape

In [ ]:
"""
    Rețineți că am fi putut furniza doar o dimensiune ca aceasta:
pm10_np = pm10_np.reshape([num_days, -1]), iar interpretul deduce singur
dimensiunea lipsă, așa cum cunoaște numărul total de elemente din matrice și
dimensiunea unei dimensiuni.
"""

## Indexarea în tablourile `numpy`

`pm10_np[:, 0]` va afișa valorile din prima locație ( prima coloană)

In [ ]:
# Să afișam valorile pentru prima locație.
pm10_np[:, 0]  # print all the values on the first column

Afișarea valorilor măsurate pentru toate locațiile, în prima zi.

In [ ]:
# Tipăriți valorile pentru toate locațiile pentru prima zi
pm10_np[0]  # aceasta este echivalentă cu scrierea pm10_np[0, :]

Afișarea valorilor măsurate pentru toate locațiile, în ultima zi.

In [ ]:
temperature_np[-1]

In [ ]:
so2_np[-1]

In [ ]:
# Tipăriți valorile pentru toate locațiile pentru ultima zi
pm10_np[-1]

IndexError: index -1 is out of bounds for axis 0 with size 0

Afișarea valorilor măsurate pentru ultima locație, în primele 7 zile.

In [ ]:
# Tipăriți valorile pentru ultima locație, pentru primele șapte zile
pm10_np[:7, -1]

In [ ]:
so2_np[:7 -1]

In [ ]:
temperature_np[:7, -1]

Afișarea valorilor măsurate pentru a treia locație, în toate zilele.
În comentariu verificăm dimensiunea pentru a fi siguri că numărul de elemente este cel corect.

In [ ]:
# Accesați valorile din a treia locație o dată la două zile
pm10_np[::2, 2]

# Verificați forma pentru a vă asigura că are numărul de elemente la care vă așteptați


In [ ]:
pm10_np[::2, 2].shape

In [ ]:
pm10_np[:10, 0]

## Indexarea cu valori logice (boolean)

Ne propunem să aflăm în câte zile valoarile măsurate pentru pm10 sunt peste un anumit prag. Vom atribui pragului o valoare pentru ca apoi să generăm o mască logică pentru fiecare index.

In [ ]:
# Să presupunem că vrem să știm în câte zile valoarea pm10 a fost peste unele
# prag critic.
# Definiți pragul
th = 60
# Generați o mască booleană pentru a indexa matricea
bmask = pm10_np>th

Afișăm valorile, după aplicarea măștii logice

In [ ]:
# imprimați masca pentru a vedea cum arată
bmask

Pentru a număra zilele în care a fost depășit pragul, însumăm valorile din masca logică. `False` va avea valoarea 0 și `True` valoarea 1

In [ ]:

# Pentru a număra numărul de zile peste prag, putem însuma peste mască.
# Fals va fi considerat 0 și Adevărat este 1.
bmask.sum()

Pentru a vedea valorile care depășesc pragul:

In [ ]:
# Pentru a vedea efectiv valorile:
pm10_np[bmask]

In [ ]:
so2_np[bmask]

## Cozile și tablourile `numpy`

Pentru simplificare, putem crea un singur tablou multi-dimensional pentru toți indicatorii. Vom folosi o strcutură de tip stivă pentru crearea unui tablou tridimensional. Pentru aceasta, trebuie să specificăm dimensiunea la care ne raportăm în crearea stivei, folosind parametrul `axis`.
Se va genera o eroare deoarece cele 3 tablouri pe care încercăm să le adăugăm în stivă nu au aceeași lungime (`shape`)

In [ ]:
"""
    Pentru comoditate, putem crea o singură matrice multi-dim pentru toți
indicatorii folosind „stiva” pentru a crea o matrice 3D. Trebuie să indicăm
dimensiunea de-a lungul căruia să stivuiți folosind parametrul „axa”.
(acest lucru are ca rezultat o eroare, vezi mai jos)
"""
all_vals = np.stack([pm10_np, so2_np, temperature_np], axis=-1)

Vom modifica tablourile `so2_np` și `temperature_np` pentru a avea aceeași structură cu a tabloului `pm10_np`

In [ ]:
"""
    Cele de mai sus au ca rezultat o eroare, deoarece tablourile pe care încercăm
să le stivuim nu au aceeași formă. Mai întâi trebuie să remodelăm „so2_np”,
„temperature_np”, pentru a avea aceeași formă ca pm10_np.
"""
so2_np = so2_np.reshape([-1, num_locations], order='F')
temperature_np = temperature_np.reshape([num_days, -1], order='F')

Modificarea se poate face și direct, prin copierea structurii.

In [ ]:
"""
    Rețineți că am fi putut folosi și acest lucru, deoarece dorim ca aceste
matrice să aibă aceeași formă
"""
so2_np = so2_np.reshape(pm10_np.shape)

Acum putem adăuga valorile în stivă.

In [ ]:
# Acum încercați din nou să stivuiți
all_vals = np.stack([pm10_np, so2_np, temperature_np], axis=-1)

O verificare a structurii ne va arată 62 de zile, pentru 17 orașe si 3 indicatori.

In [ ]:
# Verificați forma
all_vals.shape

## Operații cu dimensiuni

După adăugarea în stivă, putem efectua seturi suplimentare de calcule.



> Media aritmetică a valorilor ${PM_{10}}$  în toate orașele, pentru toate zilele:



In [ ]:
# Să vedem media pentru toate nivelurile pm10 din toate orașele în toate zilele
np.mean(all_vals[:, :, 0])

>Media artimetică a valorilor ${PM_{10}}$  pentru fiecare oraș:

In [ ]:
# Let's see the average over all pm10 levels in every city
np.mean(all_vals[:, :, 0], axis=0)

>Cele mai mari valori înregistrate în fiecare oraș:

In [ ]:
# Să vedem media pentru toate nivelurile pm10 din fiecare oraș
np.max(all_vals[:, :, 0], axis=0)

## Vizualizare

Vom reprezenta grafic valorile ${PM_{10}}$ înregistrate pentru toate locațiile, în toate zilele: folosim culori deschise pentru valorile mari și culori mai închise pentru valorile scăzute.

In [ ]:
"""
    Putem reprezenta datele pentru toate locațiile în toate zilele pentru a
avea o vedere globală. Utilizarea „fierbinte” ca hartă de culori va desena în
culori strălucitoare valorile mari și în culori închise valorile scăzute.
"""
import matplotlib.pyplot as plt
plt.imshow(pm10_np, cmap='hot', interpolation='nearest')
plt.xlabel('Locations')
plt.ylabel('Days')
plt.title('PM10 between end of December 2020 and end of February 2021')
plt.show()

Reprezentarea pentru ${SO_2}$ este:

In [ ]:
plt.imshow(so2_np,cmap='hot', interpolation='nearest')
plt.xlabel('Locations')
plt.ylabel('Days')
plt.title('SO2 between end of December 2020 and end of February 2021')
plt.show()

In [ ]:
plt.imshow(temperature_np, cmap='hot', interpolation='nearest')
plt.xlabel('Locations')
plt.ylabel('Days')
plt.title('Temperature between and of December 2020 and end of February 2021')
plt.show()

In [ ]:
# să ne uităm la nivelurile de SO2
plt.imshow(so2_np, cmap='hot', interpolation='nearest')
plt.xlabel('Locations')
plt.ylabel('Days')
plt.title('SO2 between end of December 2020 and end of February 2021')
plt.show()

Reprezentarea pentru temperatură:

In [ ]:
# să ne uităm și la temperatură
plt.imshow(temperature_np, cmap='hot', interpolation='nearest')
plt.xlabel('Locations')
plt.ylabel('Days')
plt.title('Temperature between end of December 2020 and end of February 2021')
plt.show()

Se poate observa o coloana atipică în reprezentarea de mai sus. Aceasta corespunde orașului Brașov, valorile fiind într-adevăr eronate, probabil din cauza unui senzor defect.

Analiza reprezentării grafice face posibilă identificare mai rapidă a erorilor pentru a le corecta.

Vom reprezenta grafic, cu ajutorul culorilor, valorile *sigure* (în nuanțe de albastru-verde) și pe cele *periculoase* (culoare roșie).
De exemplu, pentru ${PM_{10}}$, legislația UE consideră că valorile mai mici de 40 de microni sunt sigure.

In [ ]:
#@title Personalizarea culorilor din hărți
# Clasa de ajutor pentru a ne permite să setăm nivelurile de culoare pe care
# le dorim, adică să spunem când o valoare este periculoasă.

import matplotlib.colors as colors
# 'matplotlib.colors' este importat pentru a extinde funcționalitățile de normalizare a culorilor.
class MidpointNormalize(colors.Normalize):
# Aceasta clasă extinde colors.Normalize.

	"""
		Normalizați bara de culori, astfel încât barele divergente să funcționeze
pe fiecare parte o valoare de mijloc prescrisă)
	e.g. im=ax1.imshow(array, norm=MidpointNormalize(midpoint=0.,vmin=-100, vmax=100))
	"""
	def __init__(self, vmin=None, vmax=None, midpoint=None, clip=False):
	# 'vmin', 'vmax', 'midpoint' și 'clip' sunt parametri care definesc intervalul
# și punctul de mijloc pentru normalizare.
		self.midpoint = midpoint
		# 'self.midpoint' este stocat pentru a fi utilizat în funcția 'call'.
		colors.Normalize.__init__(self, vmin, vmax, clip)
		# Constructorul părintelui colors.Normalize este apelat pentru a inițializa
# restul parametrilor.

	def __call__(self, value, clip=None):
		# Ignor valorile mascate și tot felul de cazuri marginale pentru a face a
# un exemplu simplu...
		x, y = [self.vmin, self.midpoint, self.vmax], [0, 0.5, 1]
		"""
			- x și y definesc punctele de referință pentru normalizare: ['self.vmin',
'self.midpoint', 'self.vmax'] și [0, 0.5, 1]. Asta înseamnă că 'self.vmin' va
fi mapat la 0, 'self.midpoint' va fi mapat la 0.5, iar 'self.vmax' va fi mapat la 1.
		"""
		# np.interp(value, x, y) efectuează interpolarea liniară a valorilor.
		# np.ma.masked_array(..., np.isnan(value)) maschează valorile NaN.
		return np.ma.masked_array(np.interp(value, x, y), np.isnan(value))

In [ ]:
# plt.imshow(pm10_np, cmap='seismic', interpolation='nearest')
plt.imshow(pm10_np, cmap='seismic', norm=MidpointNormalize(midpoint=40))
plt.xlabel('Locations')
plt.ylabel('Days')
plt.title('PM10 between end of December 2020 and end of February 2021')
plt.show()

Afișarea datelor pentru un anumit oraș: București - al șaselea în lista

In [ ]:
import datetime
points = pm10_np[:, 5]
mask_safe = np.array(points < 40)
mask_unsafe = np.array(points >= 40)
plt.bar(np.array(range(len(points)))[mask_safe], points[mask_safe], width=0.4, color='b')
plt.bar(np.array(range(len(points)))[mask_unsafe], points[mask_unsafe], width=0.4, color='r')
plt.title('PM10 values in Bucharest')
plt.show()

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
# reprezentați grafic valorile pentru un anumit oraș, de ex. București, locul 6 în top
import datetime
points = pm10_np[:, 5]
# pentru a afișa cu roșu zilele cu valori periculoase, folosim indexarea booleană
mask_safe = np.array(points < 40)
mask_unsafe = np.array(points >= 40)
plt.bar(np.array(range(len(points)))[mask_safe], points[mask_safe], width=0.4, color='b')
plt.bar(np.array(range(len(points)))[mask_unsafe], points[mask_unsafe], width=0.4, color='r')
plt.title('PM10 values in Bucharest')
plt.show()

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Afișarea detelor pentru Arad, primul în listă:

In [ ]:
# compară asta cu de ex. Arad, locul 1 pe listă
import datetime
points = pm10_np[:, 0]
mask_safe = np.array(points < 40)
mask_unsafe = np.array(points >= 40)
plt.bar(np.array(range(len(points)))[mask_safe], points[mask_safe], width=0.4, color='b')
plt.bar(np.array(range(len(points)))[mask_unsafe], points[mask_unsafe], width=0.4, color='r')
plt.title('PM10 values in Arad')
plt.show()

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

## Temă
Fiind date coordonatele (latitudine, longitudine) mai multor locații, să se creeze și să se afișeze o hartă pentru diferiți indicatori

In [ ]:
# locations latitude and longitude
locations = {}
locations[f'Ploiești'] = (44.9333, 26.0333)
locations[f'Craiova'] = (44.3193, 23.8006)
locations[f'Bacău'] = (46.5688, 26.9160)
locations[f'Râmnicu Vâlcea'] = (45.0997, 24.3693)
locations[f'Sibiu'] = (45.7936, 24.1213)
locations[f'Timișoara'] = (45.7606, 21.2267)
locations[f'Piteşti'] = (44.8565, 24.8692)
locations[f'Arad'] = (46.1866, 21.3123)
locations[f'Cluj-Napoca'] = (46.7704, 23.5914)
locations[f'Bucharest'] = (44.4396, 26.0963)
locations[f'Baia Mare'] = (47.6567, 23.5850)
locations[f'Oradea'] = (47.0465, 21.9189)
locations[f'Galaţi'] = (45.4353, 28.0080)
locations[f'Brașov'] = (45.6579, 25.6011)
locations[f'Iași'] = (47.1635, 27.5825)
locations[f'Constanţa'] = (44.1598, 28.6348)
locations[f'Brăila'] = (45.2652, 27.9595)

# Mai multe despre `numpy`

##Broadcasting

In [ ]:
# Importarea bibliotecii 'numpy'
import numpy as np
# Crearea unui array numpy bidimensional:
ar = np.array([
    [0, 1],
    [6, 2]
])

Termenul *broadcasting* se referă la abilitatea `NumPy` de a lucra cu tablouri de diferite dimensiuni în cadrul operațiilor aritmetice. În matematică, calculele sunt posibile între tablouri de aceleași dimensiuni. În Python, dacă două tablouri nu au aceeași dimensiune, operația se va efectua prin adaptarea dimensiunilor astfel încât să devină posibilă efectuarea calculului aritmetic.

In [ ]:
"""
    Funcția np.minimum din biblioteca numpy compară elementele unui array cu un
alt array sau cu o valoare scalară și returnează un nou array care conține
valorile minime din aceste comparații. În acest caz, fiecare element din array-ul
ar va fi comparat cu valoarea scalară 3.5.
"""
np.minimum(ar, 3.5)

array([[0. , 1. ],
       [3.5, 2. ]])

Numpy convertește automat valoarea numerică `3.5` într-un tablou cu aceeași dimensiune cu a tabloului `ar`. Transformarea este necesară pentru a putea calcula valoarea minimă.


![table](https://drive.google.com/uc?export=view&id=174Yjs08xsE4Rz7dt2k5CFT8wy7ppddSY)


Conversia implicită poate scuti scrierea liniilor de cod, dar în cazuri mai complexe trebuie să se înțeleagă bine regulile aplicate.

Câteva referințe puteți găsi la:

* [Pagina Numpy despre conversie - broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)
* [Broadcasting cu exemple vizuale](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)



>În continuare vom oferi câteva exemple utile de conversii.

In [ ]:
# Centrarea matricei noastre.
print('centered array:\n', ar - np.mean(ar))

centered array:
 [[-2.25 -1.25]
 [ 3.75 -0.25]]


Observați că `np.mean()`, deși este o valoare numerică, este scăzută automat din fiecare element al tabloului.


Putem defini propria funcție pentru calculul valorii minime.

In [ ]:
clipped_ar = ar.copy()  # So that ar is not modified.
clipped_ar[clipped_ar > 3.5] = 3.5
clipped_ar

array([[0, 1],
       [3, 2]])

Ce se execută:

1. 3.5 este distribuit în relația de inegalitate (>)
2. Operatorul > definește un selector care va extrage o submulțime ce respectă condiția >.
3. 3.5 a fost distribuit la numărul corect de elemente în atribuire.

Vectorii pot fi convertiți în matrice.

In [ ]:
vec = np.array([1, 2])
ar + vec

array([[1, 3],
       [7, 4]])

Dimensiunile tablourilor sunt:
```
ar     (2d array):  2 x 2
vec    (1d array):      2
Result (2d array):  2 x 2
```

Când oricare din dimensiunile comparate este 1 ( chiar și implicit, ca în cazul tabloului `vec`), se folosește cealaltă dimensiune. Altfel spus, dimnensiunile egale cu 1 sunt ajustate sau copiate astfel încât să se potrivească celorlalte dimensiuni .

în cazul de mai sus, linia `[1, 2]` se repetă de mai multe ori pentru a se potrivi numărului de linii din `ar`, pentru ca apoi să se efectueze adunarea.

Dacă va fi o neconcordanță între dimensiuni, compilarorul va genera eroare.  


Decomentatți linia de mai jos și rulați programul.

In [ ]:
ar + np.array([[1, 2, 3]])

ValueError: operands could not be broadcast together with shapes (2,2) (1,3) 

#### Exercițiu

Transformați și însumați vectorul `[10, 20, 30]` în concordanță cu coloanele din tabloul `ar`.

Ar trebui să obțineți un rezultat similar cu:
```
array([[10. , 10.2],
       [20.9, 20.5],
       [30.3, 30.7]])
 ```


In [ ]:
vec = np.array([[10], [20], [30]])
ar + vec

ValueError: operands could not be broadcast together with shapes (2,2) (3,1) 

##Numere aleatoare

Sunt situații în care trebuie să generăm numere aleatoare, cum ar fi, de exmplu, inițializarea parametrilor unei rețele neuronale la începutul antrenamentului.
În mod normal, calculatoarele nu pot genera cu adevărat numere aleatoare.

Mai degrabă se generează valori pseudo-aleatoare, valori ce par a fi alese la întâmplare, deși succesiunea poate fi intuită datorită inițializărilor făcute(cele de pornire).

Pentru a genera secvențe aleatoare și calculele reproductibile, trebuie să inițializăm valoarea de pornire și să folosim aceeași valoare.

* funcția [`np.random.seed()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.seed.html) inițializează valoarea de start, sau
* clasa [`np.random.RandomState`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.html) , care este un container pentru numere generate pseudo-aleator și oferă metode pentru generarea aleatoare a numerelor.


In [ ]:
np.random.seed(0)
print("   >>  Setting the random seed to 0")
print(np.random.random())
print(np.random.random())
print(np.random.random())
# Reset the global random state to the same state.
np.random.seed(0)
print("  >>  Resetting the random seed to 0")
print(np.random.random())
print(np.random.random())
print(np.random.random())

# Generating an array of size 2x2x3
print (np.random.random(size=(2,2,3)))

   >>  Setting the random seed to 0
0.5488135039273248
0.7151893663724195
0.6027633760716439
  >>  Resetting the random seed to 0
0.5488135039273248
0.7151893663724195
0.6027633760716439
[[[0.54488318 0.4236548  0.64589411]
  [0.43758721 0.891773   0.96366276]]

 [[0.38344152 0.79172504 0.52889492]
  [0.56804456 0.92559664 0.07103606]]]



Pentru a permuta aleator o secvență sau pentru a returna o permutare a unui domeniu de valori, vom folosi `random.permutation`


>` random.permutation(x)`

Dacă x este un tablou multidimensional, permutarea se va efectua doar de-alungul primului index.

Permutarea valorilor dintr-un domeniu de valori:

In [ ]:
np.random.permutation(10)

array([5, 1, 8, 2, 6, 7, 0, 3, 4, 9])

Permutarea valorilor dintr-un vector

In [ ]:
np.random.permutation([1, 4, 9, 12, 15])

array([ 1, 15,  9,  4, 12])

Permutarea într-un tablou multi-dimensional

In [ ]:
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.random.permutation(arr)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# Concluzii

Ne-am familiarizat cu `numpy`, o librărie Python puternică pentru operarea tablourilor multi-dimensionale.
Împreună cu librăria `matplotlib` studiată în lecția anterioară, se pot crea unelte vizuale utile în investigarea datelor multi-dimensionale.